INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (1001, 'ROHIT SHARMA', 'MUMBAI', '1990-09-04 10:30:45.345');
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (1002, 'MS DHONI', 'HYDERABAD', '1987-04-20 08:20:15.335');
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (1003, 'BHUVANESHWAR KUMAR', 'HYDERABAD', '1989-01-13 12:50:55.142');
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (1004, 'MOHAMMED SHAMI', 'BANGALORE', '1988-03-08 16:33:40.678');
INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE) VALUES (1005, 'HARDHIK PANDYA', 'DELHI', '1991-02-12 18:10:35.046');
INSERT INTO COURSE (id, course_name, created_timestamp, last_updated_timestamp) VALUES (901, 'SpringBoot', sysdate, sysdate);
INSERT INTO COURSE (id, course_name, created_timestamp, last_updated_timestamp) VALUES (902, 'Hadoop', sysdate, sysdate);
INSERT INTO COURSE (id, course_name, created_timestamp, last_updated_timestamp) VALUES (903, 'Spark', sysdate, sysdate);
INSERT INTO COURSE (id, course_name, created_timestamp, last_updated_timestamp) VALUES (904, 'Kafka', sysdate, sysdate);
INSERT INTO COURSE (id, course_name, created_timestamp, last_updated_timestamp) VALUES (905, 'Java', sysdate, sysdate);